# Убираем задержку после нажатия Esc (важно для Vim)
# set -s escape-time 100
# set -g repeat-time 4000

# Увеличиваем историю буфера (по умолчанию 2000)
set -g history-limit 10000

# Время циферок при выборе панели
set -g display-panes-time 3000

# Включаем мышь (выделение, скролл, переключение панелей)
set -g mouse on

# Разрешаем truecolor (если терминал поддерживает)
set -g default-terminal "screen-256color"

# Сортировка по имени
bind s choose-tree -sZ -O name

# Изменение индексов
set -g base-index 1
setw -g pane-base-index 1

unbind r
bind r source-file ~/.tmux.conf  

# Более удобное разделение окон
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Переключение между панелями стрелками
bind -r h select-pane -L
bind -r l select-pane -R
bind -r k select-pane -U
bind -r j select-pane -D

bind -r M-h resize-pane -L 5
bind -r M-l resize-pane -R 5
bind -r M-k resize-pane -U 2
bind -r M-j resize-pane -D 2

# Быстрое закрытие панели
bind x kill-pane

# Переключение между окнами
bind -r n next-window
bind -r p previous-window

# Создание и удаление окон
bind c new-window
bind & kill-window


### ---------- Копирование и вставка ----------

# Включаем режим копирования мышью и клавиатурой (vim-стиль)
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Копировать в системный буфер (работает с xclip / pbcopy)
bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"

# Префикс
set -g prefix C-a
bind C-a send-prefix

# Плагины
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'    # сохраняет сессии
set -g @plugin 'tmux-plugins/tmux-continuum'    # автосохранение сессий
set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/double/green'

# Старт плагинов
run '~/.tmux/plugins/tpm/tpm'

