cursor #dde1e6
cursor_text_color #f2f4f8

foreground            #dde1e6
background            #121212
selection_foreground  #161616
selection_background  #ff7eb6
url_color             #08bdba

color0   #161616
color1   #e1540a
color2   #08bd16
color3   #ecda00
color4   #00b3b0
color5   #005756
color6   #08bdba
color7   #afc6c6
color8   #6c7d7d
color9   #ff8947
color10  #4ae256
color11  #fff254
color12  #26cfcd
color13  #50f5f2
color14  #91fffd
color15  #f2fffe
