[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=cba6f7ff
input=cdd6f4ff
placeholder=6c7086ff
match=f5c2e7ff
; selection=313244ff
; selection-text=cdd6f4ff
selection=a6e3a1ff
selection-text=000000ff
; selection-match=f5c2e7ff
selection-match=ff0000ff
counter=9399b2ff
border=cba6f7ff

[main]
font=Monospace:size=8
lines=12
width=30
dpi-aware=yes
show-actions=yes
fuzzy=yes
filter-desktop=no

[border]
width=2
radius=8

[icon-theme]
theme=Papirus

[search]
delimiter=/
