[ids]
*

[main]
# Caps Lock: hold = Control, tap = Escape
capslock = overload(control, A-capslock)

# Control работает как Caps Lock (если нужно)
leftcontrol = capslock

# Space: hold = слой vim, tap = space
space = overload(vim, space)

# Меняем Alt и Meta корректно
leftalt = layer(meta)
leftmeta = layer(alt)
rightalt = layer(control)
f23 = noop
# =========================
# Vim layer (momentary)
# =========================

[vim]

# Vim-стрелки
h = left
j = down
k = up
l = right

# Навигация по словам
b = C-left
w = C-right

# Начало/конец строки
0 = home
4 = end

# Удаление
x = delete
d = backspace

# Shift + hjkl
leftshift+h = S-left
leftshift+j = S-down
leftshift+k = S-up
leftshift+l = S-right
